import { useState } from 'react';
import { useRouter } from 'next/router';
import api from '../services/api';
import Link from 'next/link';
import { LogIn, Zap, Eye, EyeOff, User, Lock, BookOpen, Brain, Sparkles } from 'lucide-react';

const FEATURES = [
  { icon: <Brain size={20} />, title: 'AI-Powered', desc: 'Questions generated by cutting-edge LLMs' },
  { icon: <BookOpen size={20} />, title: 'Any Topic', desc: 'From physics to poetry — no limits' },
  { icon: <Sparkles size={20} />, title: 'Track Progress', desc: 'Review scores and retake to improve' },
];

export default function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [showPw, setShowPw] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  const registered = router.query?.registered === 'true';

  const handleLogin = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const res = await api.post('/auth/login', { username, password });
      localStorage.setItem('access_token', res.data.access);
      localStorage.setItem('refresh_token', res.data.refresh);
      router.push('/');
    } catch (err) {
      if (!err.response) setError('Could not connect to the server. Please try again.');
      else if (err.response?.data?.detail) setError(err.response.data.detail);
      else setError('Invalid username or password.');
    } finally { setLoading(false); }
  };

  return (
    <div style={{ height: '100vh', display: 'flex', background: '#0a0a0a', overflow: 'hidden' }}>
      <style>{`
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        @keyframes float { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-16px)} }
        @keyframes pulse-ring { 0%{transform:scale(0.9);opacity:0.6} 100%{transform:scale(1.3);opacity:0} }
        .auth-input { width: 100%; padding: 14px 16px 14px 48px; font-size: 15px; background: rgba(255,255,255,0.04); border: 1.5px solid rgba(255,255,255,0.08); border-radius: 14px; color: white; outline: none; transition: all 0.2s; font-family: inherit; box-sizing: border-box; }
        .auth-input::placeholder { color: rgba(255,255,255,0.2); }
        .auth-input:focus { border-color: rgba(167,139,250,0.5); background: rgba(167,139,250,0.05); }
      `}</style>

      {/* LEFT: Visual Panel */}
      <div style={{ flex: '0 0 48%', background: 'linear-gradient(135deg, #0d0b24 0%, #130f40 50%, #0f0c2e 100%)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '60px', position: 'relative', overflow: 'hidden', borderRight: '1px solid rgba(255,255,255,0.05)' }}>
        {/* Orb decorations */}
        <div style={{ position: 'absolute', width: '500px', height: '500px', borderRadius: '50%', background: 'radial-gradient(circle, #6c63ff, transparent)', top: '-200px', left: '-200px', opacity: 0.25, filter: 'blur(60px)', pointerEvents: 'none' }} />
        <div style={{ position: 'absolute', width: '400px', height: '400px', borderRadius: '50%', background: 'radial-gradient(circle, #a78bfa, transparent)', bottom: '-150px', right: '-150px', opacity: 0.2, filter: 'blur(80px)', pointerEvents: 'none' }} />
        {/* Grid pattern */}
        <div style={{ position: 'absolute', inset: 0, backgroundImage: 'linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px)', backgroundSize: '50px 50px', pointerEvents: 'none' }} />

        <div style={{ position: 'relative', zIndex: 1, textAlign: 'center', maxWidth: '400px' }}>
          {/* Logo */}
          <div style={{ position: 'relative', display: 'inline-block', marginBottom: '48px' }}>
            <div style={{ position: 'absolute', inset: '-12px', borderRadius: '28px', background: 'rgba(108,99,255,0.3)', animation: 'pulse-ring 2s ease-out infinite' }} />
            <div style={{ width: '80px', height: '80px', borderRadius: '24px', background: 'linear-gradient(135deg, #6c63ff, #a78bfa)', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 0 60px rgba(108,99,255,0.5)', position: 'relative', animation: 'float 4s ease-in-out infinite' }}>
              <Zap size={36} color="white" fill="white" />
            </div>
          </div>

          <h1 style={{ fontSize: '42px', fontWeight: 900, color: 'white', marginBottom: '16px', letterSpacing: '-0.02em', lineHeight: 1.1 }}>
            Quiz<span style={{ background: 'linear-gradient(135deg, #a78bfa, #6c63ff)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>AI</span>
          </h1>
          <p style={{ color: 'rgba(255,255,255,0.5)', fontSize: '17px', lineHeight: 1.6, marginBottom: '56px' }}>
            Generate intelligent quizzes on any topic with the power of AI.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', textAlign: 'left' }}>
            {FEATURES.map((f, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '16px', padding: '18px 20px', borderRadius: '16px', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.07)', backdropFilter: 'blur(10px)' }}>
                <div style={{ width: '40px', height: '40px', minWidth: '40px', borderRadius: '12px', background: 'rgba(167,139,250,0.15)', border: '1px solid rgba(167,139,250,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#a78bfa' }}>{f.icon}</div>
                <div>
                  <div style={{ fontSize: '15px', fontWeight: 700, color: 'white', marginBottom: '4px' }}>{f.title}</div>
                  <div style={{ fontSize: '13px', color: 'rgba(255,255,255,0.45)' }}>{f.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* RIGHT: Form Panel */}
      <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '60px 48px', overflowY: 'auto' }}>
        <div className="fade-in-up" style={{ width: '100%', maxWidth: '400px' }}>
          <div style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '30px', fontWeight: 900, color: 'white', marginBottom: '8px', letterSpacing: '-0.01em' }}>Welcome back</h2>
            <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '15px' }}>Sign in to your QuizAI account</p>
          </div>

          {registered && (
            <div style={{ background: 'rgba(52,211,153,0.1)', border: '1px solid rgba(52,211,153,0.3)', borderRadius: '12px', padding: '14px 16px', color: '#34d399', fontSize: '14px', marginBottom: '24px', fontWeight: 600 }}>
              ✓ Account created! Sign in below.
            </div>
          )}
          {error && (
            <div style={{ background: 'rgba(248,113,113,0.1)', border: '1px solid rgba(248,113,113,0.3)', borderRadius: '12px', padding: '14px 16px', color: '#fca5a5', fontSize: '14px', marginBottom: '24px' }}>
              ⚠️ {error}
            </div>
          )}

          <form onSubmit={handleLogin} style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <div>
              <label style={{ display: 'block', fontSize: '12px', fontWeight: 700, color: 'rgba(255,255,255,0.45)', marginBottom: '10px', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Username</label>
              <div style={{ position: 'relative' }}>
                <div style={{ position: 'absolute', left: '14px', top: '50%', transform: 'translateY(-50%)', color: '#a78bfa' }}><User size={18} /></div>
                <input type="text" required value={username} onChange={e => setUsername(e.target.value)} placeholder="your_username" className="auth-input" />
              </div>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '12px', fontWeight: 700, color: 'rgba(255,255,255,0.45)', marginBottom: '10px', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Password</label>
              <div style={{ position: 'relative' }}>
                <div style={{ position: 'absolute', left: '14px', top: '50%', transform: 'translateY(-50%)', color: '#a78bfa' }}><Lock size={18} /></div>
                <input type={showPw ? 'text' : 'password'} required value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" className="auth-input" style={{ paddingRight: '48px' }} />
                <button type="button" onClick={() => setShowPw(!showPw)} style={{ position: 'absolute', right: '14px', top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', cursor: 'pointer', color: 'rgba(255,255,255,0.3)', display: 'flex', padding: 0 }}>
                  {showPw ? <EyeOff size={17} /> : <Eye size={17} />}
                </button>
              </div>
            </div>

            <button type="submit" disabled={loading} style={{ width: '100%', padding: '17px', borderRadius: '14px', border: 'none', background: loading ? 'rgba(108,99,255,0.4)' : 'linear-gradient(135deg, #6c63ff, #a78bfa)', color: 'white', fontSize: '16px', fontWeight: 700, cursor: loading ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', boxShadow: loading ? 'none' : '0 8px 30px -8px rgba(108,99,255,0.6)', transition: 'all 0.2s', marginTop: '8px' }}>
              {loading ? <><svg style={{ animation: 'spin 1s linear infinite', width: '18px', height: '18px' }} viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" stroke="rgba(255,255,255,0.3)" strokeWidth="3"/><path d="M12 2a10 10 0 0 1 10 10" stroke="white" strokeWidth="3" strokeLinecap="round"/></svg> Signing in...</> : <><LogIn size={18} /> Sign In</>}
            </button>
          </form>

          <p style={{ textAlign: 'center', marginTop: '32px', fontSize: '14px', color: 'rgba(255,255,255,0.35)' }}>
            No account yet?{' '}
            <Link href="/register" style={{ color: '#a78bfa', fontWeight: 700, textDecoration: 'none' }}>Create one →</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
