# Generated by Django 5.2.12 on 2026-03-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
